[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.5.1"

[[constraint]]
  name = "github.com/aws/aws-sdk-go-v2"
  version = "0.20.0"

[[constraint]]
  name = "go.mongodb.org/mongo-driver"
  version = "1.3.2"

[prune]
  go-tests = true
  unused-packages = true